# Generated by Django 3.0.8 on 2020-07-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('flight', models.ManyToManyField(blank=True, related_name='passenger', to='Flight_App.Flight')),
            ],
        ),
    ]
